name: format

on: [push, pull_request]

jobs:
  format:
    strategy:
      matrix:
        python-version:
          - '3.12'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install --upgrade setuptools
        pip3 install .[dev]

    - name: Run --version
      run: np --version

    - name: Run pylint
      run: pylint --rcfile=setup.cfg onlinejudge_command tests setup.py

    - name: Run isort
      run: isort --check-only --diff onlinejudge_command tests setup.py

    - name: Run yapf
      run: yapf --diff --recursive onlinejudge_command tests setup.py

    - name: Run mypy
      run: mypy onlinejudge_command tests setup.py
